// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameKccl = "kccl"

// Kccl mapped from table <kccl>
type Kccl struct {
	KCAAA  string  `gorm:"column:KCAAA" json:"KCAAA"`
	KCC    string  `gorm:"column:KCC" json:"KCC"`
	PKCE   string  `gorm:"column:PKCE" json:"PKCE"`
	PKCABF float64 `gorm:"column:PKCABF" json:"PKCABF"`
	PKCABA float64 `gorm:"column:PKCABA" json:"PKCABA"`
	PKCABB float64 `gorm:"column:PKCABB" json:"PKCABB"`
	PKCABC float64 `gorm:"column:PKCABC" json:"PKCABC"`
	PKCABD float64 `gorm:"column:PKCABD" json:"PKCABD"`
	PKCABT float64 `gorm:"column:PKCABT" json:"PKCABT"`
	PKCABU float64 `gorm:"column:PKCABU" json:"PKCABU"`
	PKCABV float64 `gorm:"column:PKCABV" json:"PKCABV"`
	数据     string  `gorm:"column:数据" json:"数据"`
}

// TableName Kccl's table name
func (*Kccl) TableName() string {
	return TableNameKccl
}
