// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameKcjj = "kcjj"

// Kcjj mapped from table <kcjj>
type Kcjj struct {
	KCAAA  string  `gorm:"column:KCAAA" json:"KCAAA"`
	JJGAH  float64 `gorm:"column:JJGAH" json:"JJGAH"`
	JJGAL  int32   `gorm:"column:JJGAL" json:"JJGAL"`
	JJGAM  string  `gorm:"column:JJGAM" json:"JJGAM"`
	JJGHD  float64 `gorm:"column:JJGHD" json:"JJGHD"`
	JJGDB  float64 `gorm:"column:JJGDB" json:"JJGDB"`
	JJGJAD float64 `gorm:"column:JJGJAD" json:"JJGJAD"`
	JJGJDF float32 `gorm:"column:JJGJDF" json:"JJGJDF"`
	JJGKC  int32   `gorm:"column:JJGKC" json:"JJGKC"`
	数据     string  `gorm:"column:数据" json:"数据"`
}

// TableName Kcjj's table name
func (*Kcjj) TableName() string {
	return TableNameKcjj
}
