// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameKcj = "kcjs"

// Kcj mapped from table <kcjs>
type Kcj struct {
	KCAAA  string  `gorm:"column:KCAAA" json:"KCAAA"`
	SWJCC  string  `gorm:"column:SWJCC" json:"SWJCC"`
	SWNB   string  `gorm:"column:SWNB" json:"SWNB"`
	GCAB   string  `gorm:"column:GCAB" json:"GCAB"`
	SWJDAC float64 `gorm:"column:SWJDAC" json:"SWJDAC"`
	SWAIA  string  `gorm:"column:SWAIA" json:"SWAIA"`
	GCCBA  string  `gorm:"column:GCCBA" json:"GCCBA"`
	GCBI   string  `gorm:"column:GCBI" json:"GCBI"`
	JJGLDA string  `gorm:"column:JJGLDA" json:"JJGLDA"`
	JJGLDB string  `gorm:"column:JJGLDB" json:"JJGLDB"`
	BCB    string  `gorm:"column:BCB" json:"BCB"`
	BPJ    int32   `gorm:"column:BPJ" json:"BPJ"`
	BPWDX  string  `gorm:"column:BPWDX" json:"BPWDX"`
	DDBWDX string  `gorm:"column:DDBWDX" json:"DDBWDX"`
	数据     string  `gorm:"column:数据" json:"数据"`
}

// TableName Kcj's table name
func (*Kcj) TableName() string {
	return TableNameKcj
}
