// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameKckc = "kckc"

// Kckc mapped from table <kckc>
type Kckc struct {
	KCAAA  string  `gorm:"column:KCAAA" json:"KCAAA"`
	QDAM   string  `gorm:"column:QDAM" json:"QDAM"`
	QDAN   string  `gorm:"column:QDAN" json:"QDAN"`
	QDAO   string  `gorm:"column:QDAO" json:"QDAO"`
	QDAC   string  `gorm:"column:QDAC" json:"QDAC"`
	QDANA  string  `gorm:"column:QDANA" json:"QDANA"`
	PKGJ   string  `gorm:"column:PKGJ" json:"PKGJ"`
	PKGDDA string  `gorm:"column:PKGDDA" json:"PKGDDA"`
	PKGDDC string  `gorm:"column:PKGDDC" json:"PKGDDC"`
	PKGDDB string  `gorm:"column:PKGDDB" json:"PKGDDB"`
	GCJDBC float64 `gorm:"column:GCJDBC" json:"GCJDBC"`
	PKGCC  float64 `gorm:"column:PKGCC" json:"PKGCC"`
	GCJDBO float64 `gorm:"column:GCJDBO" json:"GCJDBO"`
	PKIIA  string  `gorm:"column:PKIIA" json:"PKIIA"`
	PKIIG  string  `gorm:"column:PKIIG" json:"PKIIG"`
	PKIIH  string  `gorm:"column:PKIIH" json:"PKIIH"`
	PKIII  string  `gorm:"column:PKIII" json:"PKIII"`
	PKIIJ  string  `gorm:"column:PKIIJ" json:"PKIIJ"`
	PKIIL  string  `gorm:"column:PKIIL" json:"PKIIL"`
	MEMO   string  `gorm:"column:MEMO" json:"MEMO"`
	数据     string  `gorm:"column:数据" json:"数据"`
}

// TableName Kckc's table name
func (*Kckc) TableName() string {
	return TableNameKckc
}
