// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameKcmc = "kcmc"

// Kcmc mapped from table <kcmc>
type Kcmc struct {
	KCAAA  string  `gorm:"column:KCAAA" json:"KCAAA"`
	MDAGA  string  `gorm:"column:MDAGA" json:"MDAGA"`
	MDBFNG float32 `gorm:"column:MDBFNG" json:"MDBFNG"`
	MDAGP  string  `gorm:"column:MDAGP" json:"MDAGP"`
	MDBEB  string  `gorm:"column:MDBEB" json:"MDBEB"`
	MDCHWK float32 `gorm:"column:MDCHWK" json:"MDCHWK"`
	MDHEAA float32 `gorm:"column:MDHEAA" json:"MDHEAA"`
	MDCDC  float32 `gorm:"column:MDCDC" json:"MDCDC"`
	MDCDF  float32 `gorm:"column:MDCDF" json:"MDCDF"`
	MDEG   string  `gorm:"column:MDEG" json:"MDEG"`
	数据     string  `gorm:"column:数据" json:"数据"`
}

// TableName Kcmc's table name
func (*Kcmc) TableName() string {
	return TableNameKcmc
}
