// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameKttz = "kttz"

// Kttz mapped from table <kttz>
type Kttz struct {
	KCAAA  string  `gorm:"column:KCAAA" json:"KCAAA"`
	PKGKI  int32   `gorm:"column:PKGKI" json:"PKGKI"`
	PKGKIA int32   `gorm:"column:PKGKIA" json:"PKGKIA"`
	PKGKDA string  `gorm:"column:PKGKDA" json:"PKGKDA"`
	PKGKJ  string  `gorm:"column:PKGKJ" json:"PKGKJ"`
	PKGKGA string  `gorm:"column:PKGKGA" json:"PKGKGA"`
	PKGKGB string  `gorm:"column:PKGKGB" json:"PKGKGB"`
	PKGKGC string  `gorm:"column:PKGKGC" json:"PKGKGC"`
	PKGKGF string  `gorm:"column:PKGKGF" json:"PKGKGF"`
	PKGKFA float32 `gorm:"column:PKGKFA" json:"PKGKFA"`
	PKGKFB float32 `gorm:"column:PKGKFB" json:"PKGKFB"`
	PKCDA  float32 `gorm:"column:PKCDA" json:"PKCDA"`
	PKGADH string  `gorm:"column:PKGADH" json:"PKGADH"`
	PKGKQ  string  `gorm:"column:PKGKQ" json:"PKGKQ"`
	KCAPA  string  `gorm:"column:KCAPA" json:"KCAPA"`
	KCAPB  string  `gorm:"column:KCAPB" json:"KCAPB"`
	KWBH   string  `gorm:"column:KWBH" json:"KWBH"`
	PKCDD  string  `gorm:"column:PKCDD" json:"PKCDD"`
	PKGKU  string  `gorm:"column:PKGKU" json:"PKGKU"`
	PKGKPH string  `gorm:"column:PKGKPH" json:"PKGKPH"`
	PKGKTA string  `gorm:"column:PKGKTA" json:"PKGKTA"`
	PKGKT  string  `gorm:"column:PKGKT" json:"PKGKT"`
	数据     string  `gorm:"column:数据" json:"数据"`
}

// TableName Kttz's table name
func (*Kttz) TableName() string {
	return TableNameKttz
}
