// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMctz = "mctz"

// Mctz mapped from table <mctz>
type Mctz struct {
	KCAAA  string  `gorm:"column:KCAAA" json:"KCAAA"`
	MDABA  string  `gorm:"column:MDABA" json:"MDABA"`
	MDAFA  int32   `gorm:"column:MDAFA" json:"MDAFA"`
	MDAFB  int32   `gorm:"column:MDAFB" json:"MDAFB"`
	MDAFH  float64 `gorm:"column:MDAFH" json:"MDAFH"`
	MDBFNG float64 `gorm:"column:MDBFNG" json:"MDBFNG"`
	MDBEB  string  `gorm:"column:MDBEB" json:"MDBEB"`
	MDDABA string  `gorm:"column:MDDABA" json:"MDDABA"`
	MDEG   string  `gorm:"column:MDEG" json:"MDEG"`
	MDAGI  string  `gorm:"column:MDAGI" json:"MDAGI"`
	MDAGO  string  `gorm:"column:MDAGO" json:"MDAGO"`
	MDABC  string  `gorm:"column:MDABC" json:"MDABC"`
	MDAGD  string  `gorm:"column:MDAGD" json:"MDAGD"`
	MDAGF  string  `gorm:"column:MDAGF" json:"MDAGF"`
	MDBLIA string  `gorm:"column:MDBLIA" json:"MDBLIA"`
	MDBK   float32 `gorm:"column:MDBK" json:"MDBK"`
	MDBMB  string  `gorm:"column:MDBMB" json:"MDBMB"`
	MDBMF  string  `gorm:"column:MDBMF" json:"MDBMF"`
	数据     string  `gorm:"column:数据" json:"数据"`
}

// TableName Mctz's table name
func (*Mctz) TableName() string {
	return TableNameMctz
}
