// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"LGIS/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/K",
				Handler: ListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)
}
